@call nggc dashboard
@call nggc clients
@call nggc client-details
@call nggc add-client
@call nggc edit-client
@call nggc navbar
@call nggc sidebar
@call nggc login
@call nggc register
@call nggc settings
@call nggc page-not-found